# Generated by Django 5.0.6 on 2024-05-31 11:01

import django.db.models.deletion
from django.db import migrations, models

def create_initial_asset_types(apps, schema_editor):
    Category  = apps.get_model('assets', 'Category')
    AssetType  = apps.get_model('assets', 'AssetType')

    # Fetch categories where is_auto_updated is False
    categories = Category.objects.filter(is_auto_updated=False)

    initial_asset_types = [
        {
            'name': 'Nakit',
            'current_price': 1,
            'description': 'Otomatik güncellenmeyen veriler, Nakit olatak değerlendirilmektedir.',
        }
    ]

    for category in categories:
        for asset_type_data in initial_asset_types:
            AssetType.objects.create(category=category, **asset_type_data)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assettype'),
    ]

    operations = [
        migrations.RunPython(create_initial_asset_types),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.currency')),
            ],
        ),
    ]
