# Generated by Django 5.0.6 on 2024-05-31 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('rate_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency_id', to='assets.currency')),
                ('to_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency_id', to='assets.currency')),
            ],
        ),
    ]
