# Generated by Django 5.0.6 on 2024-05-31 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('buy_unit_price', models.FloatField()),
                ('number', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.account')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assettype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.currency')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.unittype')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.currency')),
            ],
        ),
    ]
